### ISSUE TITLE
Show error message that it needs parameters, when doing megdc cephinstall

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/megdc#213]
I tried `megd cephinstall` without any parameters, it shows the below error.

```
root@f484:~# megdc cephinstall

    ███╗   ███╗███████╗ ██████╗ ██████╗  ██████╗
    ████╗ ████║██╔════╝██╔════╝ ██╔══██╗██╔════╝
    ██╔████╔██║█████╗  ██║  ███╗██║  ██║██║
    ██║╚██╔╝██║██╔══╝  ██║   ██║██║  ██║██║
    ██║ ╚═╝ ██║███████╗╚██████╔╝██████╔╝╚██████╗
    ╚═╝     ╚═╝╚══════╝ ╚═════╝ ╚═════╝  ╚═════╝
starting install ⠏
Packages
CephInstall
Options
CephUser    megdc
CephPassword    megdc
PhyDev  eth0

---
panic: empty path given to mkdir

goroutine 1 [running]:
panic(0x703980, 0xc8200e8820)
    /home/ranjitha/software/go/src/runtime/panic.go:464 +0x3e6
github.com/megamsys/megdc/templates/ubuntu.Mkdir(0x0, 0x0, 0x0, 0x0, 0x1ed, 0x2)
    /home/ranjitha/code/megam/workspace/packager/megammegdc/build/trusty/megdc/src/github.com/megamsys/megdc/templates/ubuntu/cmd_fileutils.go:12 +0xae
github.com/megamsys/megdc/templates/ubuntu.(*UbuntuCephInstallTemplate).Render(0xc8200987d0, 0x7f84a8d4b420, 0xc8200710c0)
    /home/ranjitha/code/megam/workspace/packager/megammegdc/build/trusty/megdc/src/github.com/megamsys/megdc/templates/ubuntu/tpl_ceph_install.go:145 +0x164c
github.com/megamsys/urknall.(*packageImpl).AddTemplate(0xc820070f00, 0xc820074f40, 0x4, 0x7f84a8d4b458, 0xc8200987d0)
    /home/ranjitha/.go/src/github.com/megamsys/urknall/package_impl.go:47 +0x2e3
github.com/megamsys/megdc/templates/ubuntu.(*UbuntuCephInstall).Render(0xc820070e80, 0x7f84a8d4b420, 0xc820070f00)
    /home/ranjitha/code/megam/workspace/packager/megammegdc/build/trusty/megdc/src/github.com/megamsys/megdc/templates/ubuntu/tpl_ceph_install.go:84 +0x1be
github.com/megamsys/urknall.renderTemplate(0x7f84a8d4b3f8, 0xc820070e80, 0xc820070e40, 0x0, 0x0)
    /home/ranjitha/.go/src/github.com/megamsys/urknall/utils.go:16 +0x153
github.com/megamsys/urknall.(*Build).prepareBuild(0xc820070ec0, 0x8bdd9d, 0x0, 0x0)
    /home/ranjitha/.go/src/github.com/megamsys/urknall/build.go:78 +0x5c
github.com/megamsys/urknall.(*Build).Run(0xc820070ec0, 0x0, 0x0)
    /home/ranjitha/.go/src/github.com/megamsys/urknall/build.go:36 +0x45
github.com/megamsys/urknall.Run(0x7f84a8d4b3b8, 0xc820074e70, 0x7f84a8d4b3f8, 0xc820070e80, 0x0, 0x0)
    /home/ranjitha/.go/src/github.com/megamsys/urknall/build.go:16 +0x9a
github.com/megamsys/megdc/templates/ubuntu.(*UbuntuCephInstall).Run(0xc820070380, 0x7f84a8d4b3b8, 0xc820074e70, 0x0, 0x0)
    /home/ranjitha/code/megam/workspace/packager/megammegdc/build/trusty/megdc/src/github.com/megamsys/megdc/templates/ubuntu/tpl_ceph_install.go:93 +0x139
github.com/megamsys/megdc/templates.(*Template).Run(0xc8200986e0, 0x0, 0x0)
    /home/ranjitha/code/megam/workspace/packager/megammegdc/build/trusty/megdc/src/github.com/megamsys/megdc/templates/template.go:80 +0x420
github.com/megamsys/megdc/handler.(*Handler).Run.func1(0xc8200986e0, 0xc820072240, 0x0, 0x0)
    /home/ranjitha/code/megam/workspace/packager/megammegdc/build/trusty/megdc/src/github.com/megamsys/megdc/handler/handler.go:84 +0x2d
github.com/megamsys/megdc/templates.RunInTemplates.func1(0x0, 0x1, 0x0, 0x0)
    /home/ranjitha/code/megam/workspace/packager/megammegdc/build/trusty/megdc/src/github.com/megamsys/megdc/templates/template.go:104 +0xdf
github.com/megamsys/megdc/templates.RunInTemplates(0xc820080078, 0x1, 0x1, 0x8bef48, 0x0, 0xc8200c5900, 0x0, 0x0)
    /home/ranjitha/code/megam/workspace/packager/megammegdc/build/trusty/megdc/src/github.com/megamsys/megdc/templates/template.go:122 +0x3b1
github.com/megamsys/megdc/handler.(*Handler).Run(0xc820070d80, 0x0, 0x0)
    /home/ranjitha/code/megam/workspace/packager/megammegdc/build/trusty/megdc/src/github.com/megamsys/megdc/handler/handler.go:89 +0x66
github.com/megamsys/megdc/packages/ceph.(*Cephinstall).Run(0xc8200707c0, 0xc820098640, 0x0, 0x0)
    /home/ranjitha/code/megam/workspace/packager/megammegdc/build/trusty/megdc/src/github.com/megamsys/megdc/packages/ceph/cephinstall.go:68 +0x172
github.com/megamsys/libgo/cmd.(*Manager).Run(0xc8200bc000, 0x0, 0x0, 0x0)
    /home/ranjitha/.go/src/github.com/megamsys/libgo/cmd/cmd.go:184 +0x1ec6
main.main()
    /home/ranjitha/code/megam/workspace/packager/megammegdc/build/trusty/megdc/src/github.com/megamsys/megdc/cmd/megdc/main.go:79 +0xba
```

**Comment by thomasalrin** [comment]
@ranjithamca it should show the "megdc cephinstall --help" message, when trying without parameters.

Also help message should stat that, what are all the parameters must be passed and what is the default value, when you don't pass any parameters.
